function dGdX = dGdX(Phi,Rho,Theta,q1,q2,q3,q4)
%DGDX
%    DGDX = DGDX(PHI,RHO,THETA,Q1,Q2,Q3,Q4)

%    This function was generated by the Symbolic Math Toolbox version 5.11.
%    06-Apr-2014 18:54:58

t2 = sin(Theta);
t3 = cos(Theta);
t4 = sin(Phi);
t5 = cos(Phi);
t6 = Rho.*q1.*t2.*2.0;
t7 = Rho.*q3.*t2.*2.0;
t8 = Rho.*q4.*t3.*t5.*2.0;
t9 = Rho.*q1.*t3.*t5.*2.0;
dGdX = reshape([1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,t7-Rho.*q4.*t3.*t4.*2.0,t8-Rho.*q2.*t2.*2.0,Rho.*q2.*t3.*t4.*2.0-Rho.*q3.*t3.*t5.*2.0,Rho.*q4.*t2.*-2.0-Rho.*q3.*t3.*t4.*2.0,-t6+Rho.*q2.*t3.*t4.*4.0-Rho.*q3.*t3.*t5.*2.0,-t8+Rho.*q2.*t2.*4.0+Rho.*q1.*t3.*t4.*2.0,t6-Rho.*q2.*t3.*t4.*2.0+Rho.*q3.*t3.*t5.*4.0,Rho.*q4.*t2.*-2.0-Rho.*q2.*t3.*t5.*2.0,-t9+Rho.*q3.*t2.*4.0-Rho.*q4.*t3.*t4.*2.0,Rho.*q2.*t2.*-2.0-Rho.*q1.*t3.*t4.*2.0+Rho.*q4.*t3.*t5.*4.0,-t7+t9+Rho.*q4.*t3.*t4.*4.0,Rho.*q2.*t3.*t5.*-2.0-Rho.*q3.*t3.*t4.*2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3, 13]);
