function dGdX = dGdX(Phi,Rho,Theta,q1,q2,q3,q4)
%DGDX
%    DGDX = DGDX(PHI,RHO,THETA,Q1,Q2,Q3,Q4)

%    This function was generated by the Symbolic Math Toolbox version 5.11.
<<<<<<< HEAD
%    06-Apr-2014 18:54:58
=======
%    21-Mar-2014 12:15:36
>>>>>>> f8cd4fdc6d1a4ebcb15e715b29fb232ef7ac911a

t2 = sin(Theta);
t3 = cos(Theta);
t4 = sin(Phi);
t5 = cos(Phi);
<<<<<<< HEAD
t6 = Rho.*q1.*t2.*2.0;
t7 = Rho.*q3.*t2.*2.0;
t8 = Rho.*q4.*t3.*t5.*2.0;
t9 = Rho.*q1.*t3.*t5.*2.0;
dGdX = reshape([1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,t7-Rho.*q4.*t3.*t4.*2.0,t8-Rho.*q2.*t2.*2.0,Rho.*q2.*t3.*t4.*2.0-Rho.*q3.*t3.*t5.*2.0,Rho.*q4.*t2.*-2.0-Rho.*q3.*t3.*t4.*2.0,-t6+Rho.*q2.*t3.*t4.*4.0-Rho.*q3.*t3.*t5.*2.0,-t8+Rho.*q2.*t2.*4.0+Rho.*q1.*t3.*t4.*2.0,t6-Rho.*q2.*t3.*t4.*2.0+Rho.*q3.*t3.*t5.*4.0,Rho.*q4.*t2.*-2.0-Rho.*q2.*t3.*t5.*2.0,-t9+Rho.*q3.*t2.*4.0-Rho.*q4.*t3.*t4.*2.0,Rho.*q2.*t2.*-2.0-Rho.*q1.*t3.*t4.*2.0+Rho.*q4.*t3.*t5.*4.0,-t7+t9+Rho.*q4.*t3.*t4.*4.0,Rho.*q2.*t3.*t5.*-2.0-Rho.*q3.*t3.*t4.*2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3, 13]);
=======
t6 = Rho.*q2.*t2.*2.0;
t7 = Rho.*q1.*t2.*2.0;
t8 = Rho.*q4.*t2.*2.0;
t9 = Rho.*q3.*t2.*2.0;
t10 = Rho.*q3.*t3.*t5.*2.0;
t11 = Rho.*q2.*t3.*t4.*2.0;
t12 = Rho.*q4.*t3.*t5.*2.0;
t13 = Rho.*q1.*t3.*t5.*2.0;
t14 = Rho.*q2.*t3.*t5.*2.0;
t15 = Rho.*q3.*t3.*t4.*2.0;
dGdX = reshape([1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,t9-Rho.*q4.*t3.*t4.*2.0,-t6+t12,-t10+t11,t8+t15,-t7+t10-Rho.*q2.*t3.*t4.*4.0,t12-Rho.*q2.*t2.*4.0+Rho.*q1.*t3.*t4.*2.0,t7+t11-Rho.*q3.*t3.*t5.*4.0,t8+t14,-t13-Rho.*q3.*t2.*4.0+Rho.*q4.*t3.*t4.*2.0,t6-Rho.*q1.*t3.*t4.*2.0-Rho.*q4.*t3.*t5.*4.0,t9+t13-Rho.*q4.*t3.*t4.*4.0,t14+t15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3, 13]);
>>>>>>> f8cd4fdc6d1a4ebcb15e715b29fb232ef7ac911a
