function dGdX = dGdX(Phi,Rho,Theta,q1,q2,q3,q4)
%DGDX
%    DGDX = DGDX(PHI,RHO,THETA,Q1,Q2,Q3,Q4)

%    This function was generated by the Symbolic Math Toolbox version 5.11.
%    26-Feb-2014 16:08:42

t2 = cos(Theta);
t3 = sin(Theta);
t4 = cos(Phi);
t5 = sin(Phi);
t6 = Rho.*q2.*t3.*2.0;
t7 = Rho.*q1.*t2.*t5.*2.0;
t19 = Rho.*q4.*t2.*t4.*2.0;
t8 = t6+t7-t19;
t9 = Rho.*q2.*t2.*t5.*2.0;
t10 = Rho.*q4.*t3.*2.0;
t11 = Rho.*q2.*t2.*t4.*2.0;
t12 = Rho.*q3.*t2.*t5.*2.0;
t13 = t10+t11+t12;
t14 = Rho.*q1.*t2.*t4.*2.0;
t15 = Rho.*q4.*t2.*t5.*2.0;
t16 = Rho.*q1.*t3.*2.0;
t17 = Rho.*q3.*t2.*t4.*2.0;
t18 = -t9+t16+t17;
t20 = Rho.*q3.*t3.*2.0;
dGdX = reshape([1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,t14+t15-Rho.*q3.*t3.*2.0,t8,t18,t13,t18,-t6-t7+t19,t9-Rho.*q1.*t3.*2.0-Rho.*q3.*t2.*t4.*2.0,t13,t14+t15-t20,t8,-t14-t15+t20,t13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3, 13]);
