function dGdZ = dGdZ(Phi,Rho,Theta,q1,q2,q3,q4)
%DGDZ
%    DGDZ = DGDZ(PHI,RHO,THETA,Q1,Q2,Q3,Q4)

%    This function was generated by the Symbolic Math Toolbox version 5.11.
%    17-Mar-2014 15:37:48

t2 = cos(Theta);
t3 = sin(Phi);
t4 = q1.*q4.*2.0;
t5 = q2.*q3.*2.0;
t6 = t4+t5;
t7 = cos(Phi);
t8 = sin(Theta);
t9 = q1.^2;
t10 = q2.^2;
t11 = q3.^2;
t12 = q4.^2;
t13 = t9+t10-t11-t12;
t14 = q1.*q3.*2.0;
t21 = q2.*q4.*2.0;
t15 = t14-t21;
t16 = t4-t5;
t17 = t9-t10+t11-t12;
t18 = q1.*q2.*2.0;
t19 = q3.*q4.*2.0;
t20 = t18+t19;
t22 = t14+t21;
t23 = t18-t19;
t24 = t9-t10-t11+t12;
dGdZ = reshape([Rho.*t2.*t6.*t7-Rho.*t2.*t3.*t13,Rho.*t2.*t3.*t16+Rho.*t2.*t7.*t17,-Rho.*t2.*t3.*t22-Rho.*t2.*t7.*t23,-Rho.*t2.*t15-Rho.*t3.*t6.*t8-Rho.*t7.*t8.*t13,Rho.*t2.*t20-Rho.*t3.*t8.*t17+Rho.*t7.*t8.*t16,Rho.*t2.*t24+Rho.*t3.*t8.*t23-Rho.*t7.*t8.*t22,-t8.*t15+t2.*t3.*t6+t2.*t7.*t13,t8.*t20+t2.*t3.*t17-t2.*t7.*t16,t8.*t24-t2.*t3.*t23+t2.*t7.*t22],[3, 3]);
