function dGdZ = dGdZ(Phi,Rho,Theta,q1,q2,q3,q4)
%DGDZ
%    DGDZ = DGDZ(PHI,RHO,THETA,Q1,Q2,Q3,Q4)

%    This function was generated by the Symbolic Math Toolbox version 5.11.
%    18-Mar-2014 15:47:51

t2 = cos(Theta);
t3 = sin(Phi);
t4 = q1.*q4.*2.0;
t16 = q2.*q3.*2.0;
t5 = t4-t16;
t6 = cos(Phi);
t7 = sin(Theta);
t8 = q3.^2;
t9 = t8.*2.0;
t10 = q4.^2;
t11 = t10.*2.0;
t12 = t9+t11-1.0;
t13 = q1.*q3.*2.0;
t14 = q2.*q4.*2.0;
t15 = t13+t14;
t17 = t4+t16;
t18 = q2.^2;
t19 = t18.*2.0;
t20 = t11+t19-1.0;
t21 = q1.*q2.*2.0;
t23 = q3.*q4.*2.0;
t22 = t21-t23;
t24 = t13-t14;
t25 = t21+t23;
t26 = t9+t19-1.0;
dGdZ = reshape([-Rho.*t2.*t5.*t6+Rho.*t2.*t3.*t12,-Rho.*t2.*t3.*t17-Rho.*t2.*t6.*t20,Rho.*t2.*t3.*t24+Rho.*t2.*t6.*t25,Rho.*t2.*t15+Rho.*t3.*t5.*t7+Rho.*t6.*t7.*t12,-Rho.*t2.*t22+Rho.*t3.*t7.*t20-Rho.*t6.*t7.*t17,-Rho.*t2.*t26-Rho.*t3.*t7.*t25+Rho.*t6.*t7.*t24,t7.*t15-t2.*t3.*t5-t2.*t6.*t12,-t7.*t22-t2.*t3.*t20+t2.*t6.*t17,-t7.*t26+t2.*t3.*t25-t2.*t6.*t24],[3, 3]);
