function dGdZ = dGdZ
%DGDZ
%    DGDZ = DGDZ

%    This function was generated by the Symbolic Math Toolbox version 5.11.
%    26-Feb-2014 16:08:43

dGdZ = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[3, 3]);
